FAIR EVA without curl
EOSC-synergy/sqaaas-tooling pull request #60
Opened 2022-04-05 13:14 UTC by ferag

2022-04-05 15:25 UTC, davrodgon approved these changes

2022-04-08 08:12 UTC, orviz requested changes

2022-04-08 08:12 UTC, orviz commented on tooling.json
> +            "fair-eva.py": {
just a comment (it is ok like that): if you want to preserve `fair-evaluator` key for this entry, you can do so and then use `"executable": "fair-eva.py"` to point to the script.

2022-04-08 08:12 UTC, orviz commented on tooling.json
> +                    "image": "QC.FAIR/Dockerfile",
when using a Dockerfile, the key is `dockerfile` (instead of `image`)

2022-04-12 12:22 UTC, orviz commented
thanks!

2022-04-12 12:22 UTC, merged